### ISSUE TITLE
Unable to run application from flutter terminal. Getting Duplicate interface definition for class 'FlutterUdidPlugin' error

### ISSUE THREAD

**Issue by ravindran-a** [GigaDroid/flutter_udid#48]
<img width="1363" alt="image" src="https://github.com/GigaDroid/flutter_udid/assets/19164536/803c0461-4032-430e-9dda-31183c9dcb82">

**Comment by GigaDroid** [comment]
This should already be fixed, please upgrade to the latest version of the plugin.

**Comment by ravindran-a** [comment]
<img width="728" alt="image" src="https://github.com/GigaDroid/flutter_udid/assets/19164536/e3c9af5f-5417-4f26-b9e5-fac0f3c03085">
@GigaDroid its not fixed. I am on the latest version of the plugin. please resolve the issue.

**Comment by GigaDroid** [comment]
Please the running `flutter clean`. Also, which flutter version are you using?

**Comment by ravindran-a** [comment]
<img width="411" alt="image" src="https://github.com/GigaDroid/flutter_udid/assets/19164536/2a4cab1a-7d16-46fe-8da9-4b1742a6d643">

**Comment by GigaDroid** [comment]
Are you using Objective-C or Swift for the iOS part of your app? Do you have any repo where I could reproduce this?

**Comment by ravindran-a** [comment]
Am using swift and there is no customizations on the iOS side. Its just default runner project created by flutter.

There is no repo yet. Will try to create one. 

Another thing to note is, this happens only when i try to run the app from flutter terminal using flutter run.

When I open the runner in xcode and run it, it works fine. No such issues arise from xcode.

**Comment by GigaDroid** [comment]
Okay please let me know once you have a repo for me to check, don't think I'll be able to trace it down with out one.
